common.gradle

Support x86 abis

---

sxr-remote-scripting/app/src/main/assets/photo.js
sxr-remote-scripting/app/src/main/assets/space_trex.js
sxr-remote-scripting/app/src/main/assets/trex.js
sxr-remote-scripting/app/src/main/assets/video.js

updating from gvr to sxr. 
SXR-DCO-Signed-off-by: Tom Flynn
tom.flynn@samsung.com

updating from gvr to sxr

---

common.gradle

gradle: fix SXRSDK_ABI_FILTER reference

---

sxr-avatar/app/src/main/java/com/samsungxr/avatardemo/AvatarMain.java

Added an argument to AvatarEvents, updated demo to use it.
This PR depends on PR#2010 of GearVRf
GearVRf DCO signed off by: Nola Donato nola.donato@samsung.com
Original PR: https://github.com/gearvrf/GearVRf-Demos/pull/649

sxr-avatar updated to new avatar API

---

sxr-polyline/app/src/main/java/com/samsungxr/polyline/SampleScript.java

SXR-DCO-1.0-Signed-off-by: Mihail Marinov m.marinov@samsung.com

sxr-polyline: fix background color in monoscopic

---

sxr-vuforia/app/build.gradle

We don't have a 64 bit version of libVuforia.so

restrict sxr-vuforia to 32 bit

---

common.gradle
gradle.properties
template/SXRApplication/app/build.gradle
template/SXRApplication/app/src/main/AndroidManifest.xml
template/SXRApplication/app/src/main/java/com/example/com/sxrapplication/MainActivity.java
template/SXRApplication/app/src/main/res/values/strings.xml
template/SXRApplication/build.gradle
template/SXRApplication/gradle/wrapper/gradle-wrapper.properties

SXR-DCO-1.0-Signed-off-by: Dmitriy Vasilev d.vasilev@samsung.com
SXR-DCO-1.0-Signed-off-by: Mihail Marinov m.marinov@samsung.com

Gradle updates from the release_v5.0 branch

---

sxr-aravatar/app/src/main/java/com/samsungxr/aravatar/AvatarMain.java
sxr-aravatar/app/src/main/java/com/samsungxr/aravatar/AvatarManager.java
sxr-aravatar/app/src/main/java/com/samsungxr/aravatar/SceneUtils.java

Detect if running ARCore and position the model back from the camera
AR drop in positions it at 0, 0, 0
New gyle model

New gyle model, fixes for arcore

---

common.gradle

Support both ARM abis for ar "backend"

---

common.gradle

- - -
SXR-DCO-1.0-Signed-off-by: Dmitriy Vasilev d.vasilev@samsung.com

Add experimental build flavors. Again

---

sxr-simplesample/app/src/main/java/com/samsungxr/simplesample/SampleActivity.java

- - -
SXR-DCO-1.0-Signed-off-by: Dmitriy Vasilev d.vasilev@samsung.com

Revert recent changes to our favorite smoketest

---

common.gradle
gradle.properties
sxr-3dcursor-simple/app/build.gradle
sxr-3dcursor/app/build.gradle
sxr-aravatar/app/build.gradle
sxr-arcore/app/build.gradle
sxr-cardboard-audio/app/build.gradle
sxr-javascript/app/build.gradle
sxr-remote-scripting/app/build.gradle
sxr-widgetlib-viewer/app/build.gradle
sxr-x3d-demo/app/build.gradle
template/SXRApplication/README.md
template/SXRApplication/app/build.gradle
tutorials/tutorial_1_simple_app/app/build.gradle
tutorials/tutorial_2_materials/app/build.gradle
tutorials/tutorial_3_model_animation/app/build.gradle
tutorials/tutorial_4_animation/app/build.gradle
tutorials/tutorial_5_controller/app/build.gradle
tutorials/tutorial_6_vr_video/app/build.gradle
tutorials/tutorial_7_component/README.md

[release_v5.0] Use 5.0 release from maven

---

sxr-javascript/app/src/main/assets/script_bundle.json

Binding target names had to be renamed too.

Fix sxr-javascript crash

---

.travis.yml
common.gradle

first crack at travis integration for the demos
SXR-DCO-Signed-off-by: Tom Flynn
tom.flynn@samsung.com

first crack at travis integration for the demos

---

sxr-avatar/app/src/main/java/com/samsungxr/avatardemo/AvatarMain.java

Add background and shadows to avatar example

---

sxr-controls/app/src/main/java/com/samsungxr/controls/Main.java

sxr-controls: fix the build

---

template/SXRApplication/app/build.gradle

[Release_v5.0] Template app build uses snapshots now

---

build.gradle
sxr-videoplayer/app/build.gradle

ExoPlayer related build fix

---

sxr-aravatar/app/src/main/java/com/samsungxr/aravatar/AvatarMain.java

Minor fixes to the AR avatar demo

sxr-aravatar: fix positioning of avatar, check for null light estimate

---

sxr-aravatar/app/src/main/java/com/samsungxr/aravatar/AvatarMain.java
sxr-aravatar/app/src/main/java/com/samsungxr/aravatar/SceneUtils.java
sxr-arcore/app/src/main/java/com/samsungxr/arcore/simplesample/SampleHelper.java
sxr-arcore/app/src/main/java/com/samsungxr/arcore/simplesample/SampleMain.java

See https://github.com/sxrsdk/sxrsdk/pull/87
SXR-DCO-1.0-Signed-off-by: Diego Azulay <diego.a@samsung.com>

Update AR demos to use the plane polygon

---

common.gradle

If the repo is missing always fetches from maven.

Fix sxr_adapter references if you don't have the SXR repo

---

common.gradle

gradle: fix detection of sxr_adapter project presence

---

sxr-arpet/app/src/main/java/com/samsungxr/arpet/manager/permission/PermissionManager.java

sxr-arpet: request storage permission too

---

common.gradle
sxr-immersivepedia/app/src/main/AndroidManifest.xml

+ immersivepedia: set the appropriate manifest attribs so it runs on the Lenovo dev

Daydream: upgrade to 1.190.0

---

sxr-shadows/app/src/main/java/com/samsungxr/sxrshadowssample/ShadowsMain.java

Makes the shadow include the feet

sxr-shadows - change shadow range to get better shadows

---

sxr-aravatar/app/build.gradle
sxr-arcore/app/build.gradle
sxr-armarker/app/build.gradle
sxr-arpet/app/build.gradle

mixedreality using apps: automatically detect local dependencies

---

sxr-arcore/app/src/main/java/com/samsungxr/arcore/simplesample/SampleActivity.java

Depends on https://github.com/sxrsdk/sxrsdk/pull/131

sxr-arcore: correctly request permissions and respond to the result

---

sxr-arpet/app/src/main/java/com/samsungxr/arpet/service/share/SharedMixedReality.java

SXR-DCO-1.0-Signed-off-by: Moiz Sonasath <m.sonasath@samsung.com>

Implement new acquireCameraImage() API

---

sxr-camera2renderscript/app/src/main/java/com/samsungxr/sxrcamera2renderscript/Camera2RenderscriptManager.java
sxr-keyboardview/app/src/main/java/com/samsungxr/keyboardview/SXRFPSCounter.java
sxr-videoplayer/app/src/main/java/com/samsungxr/videoplayer/component/video/player/Player.java

Depends on https://github.com/sxrsdk/sxrsdk/pull/144

Use ExternalImage instead of ExternalTexture

---

sxr-widgetlib-viewer/app/build.gradle
sxr-widgetlib-viewer/app/src/main/java/com/samsungxr/widgetlibviewer/ViewerMain.java

SXR DCO signed off by: nola.donato@samsung.com Nola Donato

fix widgetlib demo for sxrsdk PR #150

---

common.gradle

Use local dependencies for the sdk if available

---

sxr-videoplayer/app/src/main/java/com/samsungxr/videoplayer/VideoPlayerApp.java
sxr-videoplayer/app/src/main/java/com/samsungxr/videoplayer/VideoPlayerMain.java

Video Player sample doesn't work. So I fixed it.

fixes Video player sample, reposition logic
